#!/bin/bash

# Resume details
name="Jonathan Schlosser"
title="Senior Data Scientist | Data Educator | Mentor"
description="Jonathan is a Senior Data Scientist at Nielsen, a Computational Social Scientist at UNC Chapel Hill, and a Data Educator with Correlation One. He has been working in data fields for over a decade and has extensive experience in media, social media, and technology domains. His data skillsets lie in the realms of Natural Language Processing, Machine Learning, and Deep Learning, with recent work in LLMs and Generative AI."

# Function to display the resume
display_resume() {
    echo "-----------------------------------------------"
    echo "Name: $name"
    echo "Title: $title"
    echo "-----------------------------------------------"
    echo ""
    echo "Description: $description"
    echo ""
    echo "Professional History:"
    echo "Nielsen"
    echo "  Senior Data Scientist - Audience Measurement, September 2021 – Present"
    echo "  - Automated and standardized A/B testing and credit analyses as a core method in team analysis."
    echo "  - Led tests and developed key tools to enhance Nielsen's data accuracy to second-level granularity."
    echo "  - Improved and standardized the analysis methodologies used to test new personal meter technology."
    echo "  - Advanced Nielsen's meter fault detection using machine learning and real-time data analysis."
    echo "  Company Info: https://www.nielsen.com/solutions/audience-measurement/#audience-measurement"
    echo ""
    echo "Correlation One"
    echo "  Lead Instructor & Technical Coach - Data Science, Machine Learning, and Data Engineering, 2021 – Present"
    echo "  - Trained 300+ junior data professionals in data science skills and concepts in Python and SQL."
    echo "  - Guided 80+ fellows through learning and applying data engineering concepts in 16+ data engineering projects."
    echo "  - Led lecture sessions to 1800+ data professionals on data science and machine learning in Python."
    echo "  - Recognized as a top instructor with one of the longest tenures."
    echo "  Company Info: https://www.correlation-one.com/"
    echo ""
    echo "UNC Odum Institute For Research In Social Science"
    echo "  Help Desk Consultant - Data Science & Statistics, 2020–2021"
    echo "  - Consulted on 150+ industry and research projects for graduate students and faculty at UNC Chapel Hill."
    echo "  - Specialized in inferential statistics, data science, and machine learning approaches in R, Python, and SPSS."
    echo "  - Recognized as a top statistics consultant and featured in a spotlight article."
    echo "  Company Info: https://odum.unc.edu/"
    echo ""
    echo "National Consortium Of Data Science"
    echo "  Teaching Assistant - Data Science, Machine Learning, & Deep Learning, 2019–2021"
    echo "  - Assisted with multiple courses on Python, Machine Learning, and Deep Learning to 50+ course participants."
    echo "  - Recognized as a top teaching assistant and was preferentially chosen for the most challenging courses."
    echo "  Company Info: https://datascienceconsortium.org/"
    echo ""
    echo "Highlights:"
    echo "Languages: SQL, Python, R"
    echo "Knowledge Areas: Data Science, Statistics, Machine Learning, Deep Learning, Natural Language Processing, Data Engineering, Large Language Models, Generative AI"
    echo "Data Science and Machine Learning: Pandas/Numpy, Matplotlib, Scikit-Learn, NLTK, Seaborn, Plotly, TensorFlow, Keras, PyTorch, HuggingFace, Streamlit, LangChain, OpenAI API"
    echo "Programming: Linux, HTML/CSS, Git/GitHub/GitLab, VSCode, CLI, Tableau, JupyterLab/Notebooks, Pip, MySQL, SQLAlchemy, PostgreSQL, Flask, Streamlit"
    echo "Cloud and DevOps: HTTP, AWS (EC2, S3, RDS, Lambda, SageMaker, Redshift), Google Cloud/Colab, Docker, Databricks, Flask, Spark/PySpark/Spark SQL, Presto/Trino, Airflow"
    echo ""
    echo "Education:"
    echo "  - PhD, Media and Communication from UNC Chapel Hill, In Progress"
    echo "  - MSc, Environment and Development from Lancaster University, 2016"
    echo "  - BS, Environmental Science from Binghamton University, 2014"
    echo ""
    echo "Links:"
    echo "  LinkedIn: https://www.linkedin.com/in/jonathanphilipschlosser/"
    echo "  GitHub: https://github.com/JPSchloss"
    echo "  Website: https://www.jonathanschlosser.com/"
    echo ""
    echo "Contact Information:"
    echo "  Email: REDACTED"
    echo "  Phone: REDACTED"
}

# Display the resume
display_resume
